# Cloudflare Worker configuration for Paras Digital Portfolio
name = "parasdigicloudflare"
compatibility_date = "2024-01-15"
main = "worker.js"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables for the worker
[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://qkokgwunjnlhssuntiob.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrb2tnd3Vuam5saHNzdW50aW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTY5NDYsImV4cCI6MjA3MDc3Mjk0Nn0.RDJzFkY7v_X9EEt2LsyH1dKz-UhSPp9-FuDUMk1xnuo"
CONTACT_TABLE_NAME = "contact_submissions"

# Secrets (these will be set via wrangler secret put)
# SUPABASE_SERVICE_ROLE_KEY
# NOTION_API_KEY  
# NOTION_DATABASE_ID
# EMAIL_HOST
# EMAIL_PORT
# EMAIL_USER
# EMAIL_PASS
# EMAIL_TO

# Worker configuration
[env.production]
name = "paras-digital-portfolio"

[env.staging]
name = "paras-digital-portfolio-staging"