# Cloudflare Pages configuration for Paras Digital Portfolio
name = "paras-digital-portfolio"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"

# Pages configuration
[pages]
# Build output directory
build_output_dir = ".next"

# Functions configuration for API routes
[functions]
# Enable functions for API routes
enabled = true

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
for = "/_next/image/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Security headers for API routes
[[headers]]
for = "/api/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
